/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class bruce_chang_javacallc_Jni */

#ifndef _Included_bruce_chang_javacallc_Jni
#define _Included_bruce_chang_javacallc_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bruce_chang_javacallc_Jni
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_bruce_chang_javacallc_Jni_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     bruce_chang_javacallc_Jni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bruce_chang_javacallc_Jni_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bruce_chang_javacallc_Jni
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_bruce_chang_javacallc_Jni_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     bruce_chang_javacallc_Jni
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bruce_chang_javacallc_Jni_checkPwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
