/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bruce_chang_ccalljava_Jni */

#ifndef _Included_com_bruce_chang_ccalljava_Jni
#define _Included_com_bruce_chang_ccalljava_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bruce_chang_ccalljava_Jni
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bruce_chang_ccalljava_Jni_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_bruce_chang_ccalljava_Jni
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bruce_chang_ccalljava_Jni_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_bruce_chang_ccalljava_Jni
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bruce_chang_ccalljava_Jni_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_bruce_chang_ccalljava_Jni
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bruce_chang_ccalljava_Jni_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
