/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bruce_chang_testndk_JniKit */

#ifndef _Included_com_bruce_chang_testndk_JniKit
#define _Included_com_bruce_chang_testndk_JniKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bruce_chang_testndk_JniKit
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bruce_chang_testndk_JniKit_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
